var define = {}

define.request_types = {
  INSERT_NEW_OPINION: 'INSERT_NEW_OPINION',
  INSERT_NEW_COMMENT: 'INSERT_NEW_COMMENT',
  DELETE_OPINION: 'DELETE_OPINION',
  DELETE_COMMENT: 'DELETE_COMMENT',
  RETRIEVE_OPINION: 'RETRIEVE_OPINION',
  RETRIEVE_OPINION_LIST: 'RETRIEVE_OPINION_LIST',
  RETRIEVE_COMMENT_LIST: 'RETRIEVE_COMMENT_LIST'
};
