var define = {}

define.request_types = {
  INSERT_NEW_POST: 'INSERT_NEW_POST',
  INSERT_NEW_COMMENT: 'INSERT_NEW_COMMENT',
  DELETE_POST: 'DELETE_POST',
  DELETE_COMMENT: 'DELETE_COMMENT',
  RETRIEVE_POST: 'RETRIEVE_POST',
  RETRIEVE_POST_LIST: 'RETRIEVE_POST_LIST',
  RETRIEVE_COMMENT_LIST: 'RETRIEVE_COMMENT_LIST'
};
