application: opinionweb-156301
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /templates
  static_dir: templates

# Endpoints handler
- url: /_ah/spi/.*
  script: backend.backend.application

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: latest

- name: endpoints
  version: 1.0
